version: '3.8'
services:
  db:
    image: postgres:16.3-alpine3.20
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=greenlight
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
volumes:
  db:
    driver: local